name: Setup Rust
description: Install Rust toolchain with specified version and components

inputs:
  rust-version:
    description: 'Rust version to install'
    required: false
    default: '1.84'
  components:
    description: 'Additional Rust components to install (comma-separated)'
    required: false
    default: 'rustfmt,clippy'
  targets:
    description: 'Additional targets to install (comma-separated)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain ${{ inputs.rust-version }}
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install components
      if: inputs.components != ''
      shell: bash
      run: |
        IFS=',' read -ra COMPONENTS <<< "${{ inputs.components }}"
        for component in "${COMPONENTS[@]}"; do
          rustup component add "$component"
        done
    
    - name: Install targets
      if: inputs.targets != ''
      shell: bash
      run: |
        IFS=',' read -ra TARGETS <<< "${{ inputs.targets }}"
        for target in "${TARGETS[@]}"; do
          rustup target add "$target"
        done
    
    - name: Verify installation
      shell: bash
      run: |
        rustc --version
        cargo --version
